spring:
  datasource:
    url: jdbc:postgresql://junction.proxy.rlwy.net:19936/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: false

